// ==UserScript==
// @name         Dyna Réception
// @namespace    local.dynareception
// @version      0.1.2
// @description  Prototype indépendant de contrôle des réceptions Dynacad.
// @match        https://dynacad.carrefour.com/*
// @updateURL    https://raw.githubusercontent.com/oreaweb/dyna-prix/main/dyna-reception.user.js
// @downloadURL  https://raw.githubusercontent.com/oreaweb/dyna-prix/main/dyna-reception.user.js
// @run-at       document-idle
// @grant        none
// ==/UserScript==

(() => {
"use strict";
let app=null, stream=null, detector=null, timer=null, orders=[], lines=[], selectedDate="";
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function cookie(n){const r=document.cookie.split("; ").find(x=>x.startsWith(n+"="));return r?decodeURIComponent(r.split("=").slice(1).join("=")):null}
function site(){for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(/^dynacad\|[^|]+\|current_store$/.test(k)){let v=localStorage.getItem(k);try{v=JSON.parse(v)}catch{};v=String(v).replace(/^"|"$/g,"").trim();if(/^\d{8,14}$/.test(v))return v}}throw Error("Magasin Dynacad non détecté")}
async function auth(){const x=cookie("XSRF-TOKEN");if(!x)throw Error("Session Dynacad introuvable");const r=await fetch("/api/authenticate",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","x-xsrf-token":x},body:"{}"});if(!r.ok)throw Error("Authentification refusée");const j=await r.json();return j.id_token}
async function api(url,opt={}){const t=await auth();const r=await fetch(url,{credentials:"include",...opt,headers:{...(opt.headers||{}),"Authorization":"Bearer "+t}});if(!r.ok)throw Error("Dynacad "+r.status);return r.json()}
async function apiSession(url,opt={}){const r=await fetch(url,{credentials:"include",...opt});if(!r.ok)throw Error("Dynacad "+r.status);return r.json()}
function fmt(d){return d?new Date(d).toLocaleDateString("fr-FR"):""}
function launcher(){if($("dr-launch"))return;const b=document.createElement("button");b.id="dr-launch";b.textContent="📦 Réception";Object.assign(b.style,{position:"fixed",left:"18px",bottom:"18px",zIndex:999998,border:"0",borderRadius:"999px",padding:"18px 24px",background:"#167332",color:"#fff",fontWeight:"800",fontSize:"18px",boxShadow:"0 5px 20px #0004",cursor:"pointer"});b.onclick=open;document.body.appendChild(b)}
async function open(){if(app){app.style.display="";return}app=document.createElement("div");app.id="dr-app";app.innerHTML=`<div style="position:fixed;inset:6px auto 6px 50%;transform:translateX(-50%);width:calc(100vw - 12px);max-width:430px;overflow:auto;box-sizing:border-box;background:white;color:#172033;z-index:1000000;padding:14px 16px;border-radius:16px;box-shadow:0 8px 35px #0005;font-family:Arial"><div style="display:flex;justify-content:space-between"><div><h2 style="margin:0">📦 Réception</h2><small style="color:#8a94a6">Prototype v0.1.2 — indépendant de Dyna Prix</small></div><button id="dr-close" style="border:0;background:none;font-size:22px">✕</button></div><div id="dr-status" style="margin:12px 0;color:#687386">Chargement des commandes…</div><div id="dr-dates"></div><div id="dr-control" style="display:none"><div id="dr-summary"></div><button id="dr-scan" style="width:100%;height:58px;margin:10px 0;background:#167332;color:white;border:0;border-radius:11px;font-size:18px;font-weight:bold">📷 Scanner un produit reçu</button><div id="dr-camera" style="display:none"><video id="dr-video" playsinline muted style="width:100%;max-height:260px;background:#000;border-radius:12px"></video><button id="dr-stop" style="width:100%;padding:10px;margin:6px 0">Arrêter la caméra</button></div><div style="display:flex;gap:6px"><input id="dr-ean" inputmode="numeric" placeholder="EAN" style="flex:1;padding:9px;font-size:16px"><button id="dr-add">Ajouter</button></div><div id="dr-last" style="margin:10px 0"></div><div id="dr-list"></div></div></div>`;document.body.appendChild(app);$("dr-close").onclick=()=>{stop();app.style.display="none"};$("dr-scan").onclick=start;$("dr-stop").onclick=stop;$("dr-add").onclick=()=>add($("dr-ean").value.trim());$("dr-ean").onkeydown=e=>{if(e.key==="Enter")add(e.target.value.trim())};await loadOrders()}
async function loadOrders(){try{const s=site(),j=await api("/api/stores/"+s+"/orders?orderStatus=VALUED",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pageIndex:0,pageSize:100,sorts:[{property:"creationDatetime",direction:"desc"}],filters:{deliverySiteGlnKey:[s]}})});orders=Array.isArray(j)?j:(j.content||j.data||[]);const ds=[...new Set(orders.map(o=>o.deliveredDate).filter(Boolean).map(x=>x.slice(0,10)))].sort().reverse();$("dr-status").textContent=ds.length?"Choisissez une date de livraison :":"Aucune livraison trouvée.";$("dr-dates").innerHTML=ds.map(d=>`<button data-date="${d}" style="width:100%;padding:13px;margin:4px 0;border:1px solid #ccd3dd;border-radius:10px;background:#fff;font-size:17px;font-weight:bold">📅 ${fmt(d+"T12:00:00")}</button>`).join("");$("dr-dates").onclick=e=>{const d=e.target.closest("[data-date]");if(d)loadDate(d.dataset.date)}}catch(e){$("dr-status").textContent="Erreur : "+e.message}}
async function loadDate(d){selectedDate=d;$("dr-status").textContent="Chargement des articles du "+fmt(d+"T12:00:00")+"…";const os=orders.filter(o=>o.deliveredDate?.slice(0,10)===d);try{const all=[];for(const o of os){const j=await apiSession("/api/orders/"+encodeURIComponent(o.prologId)+"/articles?idType=PROLOGSUBID&prologId="+encodeURIComponent(o.prologSubId),{method:"GET",headers:{"Accept":"application/json"}});const a=Array.isArray(j)?j:(j.content||j.data||[]);a.forEach(x=>all.push({...x,_order:o.shortId}))}const m=new Map();for(const x of all){const e=String(x.barcode||"");if(!e)continue;const pcb=Number(x.pcb)||1,exp=(Number(x.invoicedQteCmd)||0)*pcb,ord=(Number(x.qteCmd)||0)*pcb;if(!m.has(e))m.set(e,{ean:e,label:(x.brandDesc?x.brandDesc+" • ":"")+(x.itemDesc||"Produit"),expected:0,ordered:0,found:0,orders:[]});const z=m.get(e);z.expected+=exp;z.ordered+=ord;z.orders.push(x._order)}lines=[...m.values()];$("dr-dates").style.display="none";$("dr-control").style.display="block";$("dr-status").textContent="";render()}catch(e){$("dr-status").textContent="Erreur articles : "+e.message}}
function render(){const total=lines.reduce((a,x)=>a+x.expected,0),found=lines.reduce((a,x)=>a+Math.min(x.found,x.expected),0),complete=lines.filter(x=>x.expected>0&&x.found>=x.expected).length,notDelivered=lines.reduce((a,x)=>a+Math.max(0,x.ordered-x.expected),0);$("dr-summary").innerHTML=`<div style="padding:10px;background:#eef4ff;border-radius:12px"><b>Réception du ${fmt(selectedDate+"T12:00:00")}</b><br>${lines.filter(x=>x.expected>0).length} références • <b>${found}/${total} UVC contrôlées</b><br>✅ ${complete} complètes • 🚚 ${notDelivered} UVC non livrées par l'entrepôt</div>`;$("dr-list").innerHTML=lines.filter(x=>x.expected>0).sort((a,b)=>(a.found>=a.expected)-(b.found>=b.expected)).map(x=>{const ok=x.found>=x.expected,over=x.found>x.expected;return `<div style="padding:9px;margin:6px 0;border-radius:10px;background:${over?"#f3eafa":ok?"#e8f7ec":"#f3f5f8"}"><b>${esc(x.label)}</b><br><small>${esc(x.ean)}</small><br><b>${x.found} / ${x.expected}</b> UVC ${over?"⚠️ EN TROP":ok?"✓ COMPLET":"— reste "+(x.expected-x.found)}</div>`}).join("")}
function add(e){if(!e)return;const x=lines.find(z=>z.ean===e);if(!x){$("dr-last").innerHTML='<div style="padding:9px;background:#fdebec;color:#b00020;border-radius:10px">⚠️ EAN '+esc(e)+' absent de cette réception</div>';return}x.found++;$("dr-ean").value="";$("dr-last").innerHTML='<div style="padding:9px;background:#e8f7ec;color:#167332;border-radius:10px">✓ '+esc(x.label)+' — '+x.found+'/'+x.expected+'</div>';if(navigator.vibrate)navigator.vibrate(70);render()}
async function start(){if(!("BarcodeDetector"in window)){alert("Scanner non pris en charge");return}try{detector=new BarcodeDetector({formats:["ean_13","ean_8","upc_a","upc_e"]});stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});$("dr-camera").style.display="block";$("dr-video").srcObject=stream;await $("dr-video").play();timer=setInterval(async()=>{try{const r=await detector.detect($("dr-video"));if(r[0]?.rawValue){const e=r[0].rawValue;stop();add(e)}}catch{}},350)}catch(e){alert("Caméra : "+e.message)}}
function stop(){if(timer)clearInterval(timer);timer=null;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;const c=$("dr-camera");if(c)c.style.display="none"}
launcher();
})();